### PR TITLE
style context box

### LINKED ISSUE #236: style context box
## User story

expanding on the work Katja has done on #154

## Acceptance criteria
- [ ] context menu appears in a fixed position on the page
- [ ] details are collapsed by default

## Implementation notes & questions

will probably need to announce to screen readers when new information becomes available

It was decided that the title would be removed so just a reference to the section number on the right.

image

image

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #236

## Description

- I ended up enforcing a single context at a time as I realized I was going to have to style for multiple then remove that and restyle.
- we probably need some validation on the inputs because we're getting context text that's an empty string (thought maybe this can be done by eye when verifying content at the end?)
- My first instinct was to use `summary` / `detail` elements for these drop downs but I didn't want to undo the existing semantic html. Hopefully I've not overly complicated this by not making the switch.
- Keyboard navigation is a bit chaotic in some places. For example, you can tab into the context box to operate the dropdowns but if you tab out of it, it's going to take you to the next focus point such as the terminal, you can't then tab back to your last position because the context doesn't exist as you've switched sections.  I think you'd probably need to tab through the whole tab list and scroll back to the same position to recover the state. I'm open to ideas about how to improve this, it technically works but it's not delightful.
- state changes are announced to screenreaders via aria-live ("Context available for  section x of y" and presence of dropdown content)

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
notes  from meeting

single "context" toggle to show all content, probably wrap everything in a details/summary element

**Comment by aaaaargZombies** [comment]
Updated to show / hide all content in one click. the code is much simpler now which is good.

**Review by katjam — APPROVED** [review]
Did you want to check for empty context string here? If not, I'm happy with manual as you suggest.

**Comment by aaaaargZombies** [comment]
@katjam  I've filtered out the empty strings at when decoding the JSON so will merge now.

**Comment by katjam** [comment]
> @katjam I've filtered out the empty strings when decoding the JSON so will merge now.

Perfect!

**Pull request merged**
