### PR TITLE
Feat/210 new content and 22 sections

### LINKED ISSUE #210: New content and 22 sections
renumber according to google doc with context

- [ ] Intro text (Main text top section 1) styled differently by Stuart (no change to section)
- [ ] #215
- [ ] #216
- [ ] Draggable gallery (5.5 before HMRC terminal) (new section 8)
- [ ] #214

1 <- 1
2 <- new
3 <- new
4 <- 2
5 <- 3
6 <- 4
7 <- 5
8 <- new
9 <- 6
10 <- 7
11 <- 8
12 <- 9.1
13 <- new
14 <- 9.2
15 <- 10
16 <- 11
17 <- 12

### PR DESCRIPTION
**Pull request by katjam**
Fixes #210 

## Description

- The last part of 210 adding new sections with designated content.
- The content of graphs and terminals can now be added via CMS

## Todo stuff that can't be set in CMS
- [ ] Correct the date ranges (and maybe other axis labels) for new graphs in sections 2 & 3

### CODE REVIEW

**Review by aaaaargZombies — APPROVED** [review]
Approve with a caveat. It looks like everything you intended to change works so perhaps it's a none issue.

I noticed there's what looks like escaped HTML (space?) making it's way into the terminal but it seems to be written into the content deliberately so maybe this is intentional.

image

**Comment by katjam** [comment]
Weird. Yes. Unrelated and probably not intentional. It's due to the way the markdown is being generated I think. We can fix in another issue. It's probably that @stuartleech wasn't sure what help text to put and that it's a required field.

**Comment by stuartleech** [comment]
Ah yeah could we make it optional? I stuck a space in to make them blank...

**Comment by katjam** [comment]
> Ah yeah could we make it optional? I stuck a space in to make them blank...

Yes we could and then need to remove the colon and make sure the words on their own make sense. If it's easy, you should just put some text in there since it is meant to be explaining how the commands are used.

**Pull request merged**
